### PR TITLE
add config.SkipIssuerCheck

### PR DESCRIPTION
**Pull request by ti**
config.SkipIssuerCheck is useful for some special projects

### CODE REVIEW

**Comment by ericchiang** [comment]
Hi ti@! This is a pretty common request that I've said no to several times in the past:

https://github.com/coreos/go-oidc/issues/121
https://github.com/coreos/go-oidc/pull/122
https://github.com/coreos/go-oidc/issues/159
https://github.com/coreos/go-oidc/pull/169
https://github.com/coreos/go-oidc/issues/183

If you're seeing an issuer mis-match, it's likely that there's some kind of misconfiguration. The issuer check is also fairly fundamental to the OpenID Connect spec. Which projects are you referring to?

**Comment by ti** [comment]
@ericchiang Thanks for your reply. But in some case, it is not Azure or something else.

for example:
    
A oidc server service, is allowed user to custom domain,  so the issuer is changed. but in these server want to check the idToken, but the issuer is dynamic. if SkipIssuerCheck is on, the auth server can check any idtoken.


i know you have some securiy concern.  but the bussiness always complex。 the SkipExpiryCheck and SkipClientIDCheck are on there anyway.

**Comment by ti** [comment]
@ericchiang Thank you very very much.

**Comment by ti** [comment]
:-D， I See

**Pull request closed without merging**
