### PR TITLE
oauth2, oidc: allow empty redirect URL.

### PR DESCRIPTION
**Pull request by yifan-gu**
/cc @sym3tri

### CODE REVIEW

**Comment by yifan-gu** [comment]
Would like to get this merged soon as I am having going to bump Godeps :)

**Comment by bobbyrullo** [comment]
Why not just url.Parse in the cases that you want to parse empty urls?

**Comment by yifan-gu** [comment]
@bobbyrullo Good point... Fixed.

**Comment by yifan-gu** [comment]
Ping?

**Pull request merged**
