### PR TITLE
oauth2: return embedded http client

### PR DESCRIPTION
**Pull request by srenatus**
This is a prerequisite to a fix for https://github.com/coreos/dex/issues/395.

Happy to add tests if you agree this is potentially mergeable.

(Things will look different with #64, but I'd be happy to help transitioning, too.)

### CODE REVIEW

**Comment by srenatus** [comment]
Could this be some rate-limit issue? `go get golang.org/x/tools/cmd/vet` works fine from here...

**Comment by ericchiang** [comment]
You can already set the http client through the [client config](https://godoc.org/github.com/coreos/go-oidc/oidc#ClientConfig). Plus this doesn't set the http client, it only returns it.

Is this trying to accomplish something else?

**Comment by bobbyrullo** [comment]
he's trying to *get* the client config not set it. see #395

**Comment by bobbyrullo** [comment]
LGTM

**Pull request merged**
