### PR TITLE
jose/oidc: allow string array in claims['aud'].

### LINKED ISSUE #18: VerifyClaims should tread 'aud' as an array of string
Currently it treats it as a single string. and the error message is unclear (what's the expected valued and actual value?)

/cc @polvi

### PR DESCRIPTION
**Pull request by yifan-gu**
Fix #18 
cc @bobbyrullo @polvi

### CODE REVIEW

**Comment by yifan-gu** [comment]
As in the spec, the 'aud' should allow an string array: http://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by polvi** [comment]
nice!

**Comment by yifan-gu** [comment]
@bobbyrullo naming fixed

**Comment by yifan-gu** [comment]
Next step is:
- pass the `aud` to server, this should be implemented in go-oidc
- pass the `aud` back in the id token claims, this should be implemented in dex

For the first one I didn't find any specification on how to pass it, so I assume it's up to us.
I plan to add a field in the client config and oauthclient config, called `audience`. Then embed the field in the url, similar to what we do for [scope](https://github.com/coreos/go-oidc/blob/master/oauth2/oauth2.go#L134) 

@bobbyrullo

**Comment by bobbyrullo** [comment]
LGTM

**Pull request merged**
